before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    # use default ldflags

archives:
  - format_overrides:
    - goos: windows
      format: zip

checksum:
  algorithm: sha512

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
